AllCops:
  TargetRubyVersion: '2.2.2'
  DisplayCopNames: true
  Exclude:
    - 'spec/speed.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 50

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 13

Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: true

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'
